export const APP_START_INIT = 'APP_START_INIT';
export const APP_FINISH_INIT = 'APP_FINISH_INIT';

export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_ERROR = 'USER_GET_ERROR';

export const USERS_GET_REQUEST = 'USERS_GET_REQUEST';
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS';
export const USERS_GET_ERROR = 'USERS_GET_ERROR';

export const ROOMS_GET_REQUEST = 'ROOMS_GET_REQUEST';
export const ROOMS_GET_SUCCESS = 'ROOMS_GET_SUCCESS';
export const ROOMS_GET_ERROR = 'ROOMS_GET_ERROR';
export const MESSAGES_GET_SUCCESS = 'MESSAGES_GET_SUCCESS';

export const INIT_SOCKET = 'INIT_SOCKET';
export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_OPEN = 'SOCKET_OPEN';
export const SOCKET_CLOSE = 'SOCKET_CLOSE';
export const SOCKET_ERROR = 'SOCKET_ERROR';
export const SOCKET_MESSAGE_RECEIVE = 'SOCKET_MESSAGE_RECEIVE';
export const SOCKET_MESSAGE_SEND = 'SOCKET_MESSAGE_SEND';
export const CHAT_COMMANDS = {
  SENDMESSAGE: 'SENDMESSAGE',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CREATECHAT: 'CREATECHAT',
  REMOVECHAT: 'REMOVECHAT',
  REGISTERUSER: 'REGISTERUSER',
  STARTGAME: 'STARTGAME',
  STOPGAME: 'STOPGAME',
  CURRENT_USER: 'CURRENT_USER',
  USERS: 'USERS',
  ROOMS: 'ROOMS',
  JOINROOM: 'JOINROOM',
};
